MONTREAL_CANADIENS = "Montreal Canadiens"
CHICAGO_BLACKHAWKS = "Chicago Blackhawks"
DETROIT_RED_WINGS = "Detroit Red Wings"
NEW_YORK_RANGERS = "New York Rangers"
TORONTO_MAPLE_LEAFS = "Toronto Maple Leafs"
BOSTON_BRUINS = "Boston Bruins"

nhl_teams_list = [MONTREAL_CANADIENS, CHICAGO_BLACKHAWKS, DETROIT_RED_WINGS,
                  NEW_YORK_RANGERS, TORONTO_MAPLE_LEAFS, BOSTON_BRUINS]
