from constants import nhl_team_names
from constants.nhl_team_names import nhl_teams_list, MONTREAL_CANADIENS
from price_management import save_end_of_day_portfolio_value
from toolkit import get_user_portfolio, get_share_price_by_team_name, get_total_value_of_user_portfolio

save_end_of_day_portfolio_value()